Review code for Milestone 3
Datagirlcmr/react-calculator pull request #3
Opened 2020-05-08 19:35 UTC by Datagirlcmr

Features
Styled the app components using CSS

2020-05-09 21:48 UTC, MauricioRobayo requested changes
Well done!

It looks great and it's coming into place, but 😥 we have to make sure all requirements are met before continuing.

- [ ] `App`, `Display` and `ButtonPanel` components use flex display mode   ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone3/useFlex.png)). Could you please use `display: flex` on the `App` and `ButtonPanel` components.
- [ ] You are not passing any color to the buttons on ButtonPanel. Your `Button` component takes the color property and it defaults to orange. Now, for the buttons that are not going to be orange, let's pass some color.

Status: __Request changes__.

2020-05-09 21:48 UTC, MauricioRobayo commented on src/components/ButtonPanel.js
> +        <Button name="Ac" />
Let's pass some color to the buttons that are not going to default to orange, for example:

```jsx
<Button name="Ac" color='#e0e0e0' />
```

2020-05-12 10:23 UTC, bellom requested changes
## Hi @Datagirlcmr   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Kindly check out my comments below;**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-05-12 10:23 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="÷" color="rgb(224, 223, 219)" />
Good job making the necessary corrections seems you did more 😄 
You don't need to add color to the signs on the right side(signs like: `÷`, `x`,  `-`, `+`, `=`), we want them to have default color which is `orange` right.
kindly remove the color 👍 

Example: `<Button name="÷" />`


After I removed `rgb` color on side signs;
![image](https://user-images.githubusercontent.com/31897434/81672968-d3c6e080-9442-11ea-8c7a-e50d9850ca71.png)

2020-05-12 10:23 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="x" color="rgb(224, 223, 219)" />
kindly remove the `rgb` color 👍

2020-05-12 10:23 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="-" color="rgb(224, 223, 219)" />
kindly remove the `rgb` color 👍

2020-05-12 10:23 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="+" color="rgb(224, 223, 219)" />
kindly remove the `rgb` color 👍

2020-05-12 10:23 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="=" color="rgb(224, 223, 219)" />
kindly remove the `rgb` color 👍

2020-05-12 13:54 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/81700379-7cd00400-9460-11ea-93e7-d71289d52d0a.jpg)
### Good to go ......

2020-05-12 22:12 UTC, merged